name: RDP via ngrok

on:
  workflow_dispatch:

jobs:
  rdp-via-ngrok:
    runs-on: windows-latest
    timeout-minutes: 3600

    env:
      NGROK_ZIP_URL: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip

    steps:
      - name: Enable Remote Desktop & Firewall
        shell: powershell
        run: |
          # Bật RDP và tắt NLA (Network Level Authentication)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # Firewall: mở port 3389 (xóa rule cũ nếu có)
          netsh advfirewall firewall delete rule name="RDP-Allow" | Out-Null
          if ($LASTEXITCODE -ne 0) { Write-Host "No existing rule found, creating new one..." }
          netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389 | Out-Null

          Restart-Service -Name TermService -Force
          Start-Sleep -Seconds 3
          Write-Host "✅ RDP enabled and firewall opened (port 3389)."

      - name: Create RDP user with strong random password
        shell: powershell
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper   = [char[]](65..90)
              Lower   = [char[]](97..122)
              Number  = [char[]](48..57)
              Special = ([char[]](33..47) + [char[]](58..64) + [char[]](91..96) + [char[]](123..126))
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue) {
            Remove-LocalUser -Name "RDP"
          }

          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"

          echo "RDP_USER=RDP" >> $env:GITHUB_ENV
          echo "RDP_PASS=$password" >> $env:GITHUB_ENV

          Write-Host "✅ User 'RDP' created successfully."

      # (giữ nguyên các bước ngrok ở phía dưới, không cần sửa)