name: windows-11-rdp-setup

on:
  workflow_dispatch:

env:
  INSTALLERS_DIR: installers
  INSTALLER_CACHE_KEY: installers-windows-v4

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Restore installer cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.INSTALLERS_DIR }}
          key: ${{ env.INSTALLER_CACHE_KEY }}

      - name: Verify installers
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if ('${{ steps.restore-cache.outputs.cache-hit }}' -ne 'true') {
            throw '⚠️ Cache chưa có. Chạy workflow cache-windows-installers trước.'
          }

          $installerPath = Join-Path $env:GITHUB_WORKSPACE $env:INSTALLERS_DIR
          foreach ($file in 'DiscordSetup.exe','BraveBrowserSetup.exe','WindsurfSetup.exe','tailscale.msi') {
            $full = Join-Path $installerPath $file
            if (-not (Test-Path $full)) {
              throw "❌ Thiếu file $file trong cache."
            }
          }

      - name: Configure local user
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $password = 'hyperdayroi'
          net user 'hyper' 2>$null
          if ($LASTEXITCODE -ne 0) {
            net user 'hyper' $password /add
          } else {
            net user 'hyper' $password
          }
          net user 'hyper' /PASSWORDCHG:NO
          wmic useraccount where "Name='hyper'" set PasswordExpires=FALSE | Out-Null
          Add-LocalGroupMember -Group "Administrators" -Member "hyper"

      - name: Enable RDP access
        shell: pwsh
        run: |
          Write-Host "🪟 Bật Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Service -Name TermService -Force

      - name: Install Tailscale
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          $ErrorActionPreference = 'Stop'
          $installerPath = Join-Path $env:GITHUB_WORKSPACE $env:INSTALLERS_DIR
          $tailscaleInstaller = Join-Path $installerPath 'tailscale.msi'
          Start-Process -FilePath msiexec.exe -ArgumentList "/i `"$tailscaleInstaller`" /qn /norestart" -Wait

          $tailscaleExe = "C:\Program Files\Tailscale\tailscale.exe"
          & $tailscaleExe up --authkey $env:TAILSCALE_AUTH_KEY --hostname ("win-" + $env:GITHUB_RUN_ID) --accept-dns=false
          $tailscaleIp = (& $tailscaleExe ip -4)[0]
          "TAILSCALE_IP=$tailscaleIp" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install Desktop Apps
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $installerPath = Join-Path $env:GITHUB_WORKSPACE $env:INSTALLERS_DIR

          Write-Host "📦 Cài Discord"
          Start-Process -FilePath (Join-Path $installerPath 'DiscordSetup.exe') -ArgumentList '/S' -Wait

          Write-Host "📦 Cài Brave Browser"
          Start-Process -FilePath msiexec.exe -ArgumentList "/i `"$installerPath\BraveBrowserSetup.exe`" /qn /norestart" -Wait

          Write-Host "📦 Cài Windsurf"
          Start-Process -FilePath (Join-Path $installerPath 'WindsurfSetup.exe') -ArgumentList '/S' -Wait

          Write-Host "📦 Cài Visual Studio Code"
          Invoke-WebRequest -Uri "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user" -OutFile "$env:TEMP\vscode.exe"
          Start-Process -FilePath "$env:TEMP\vscode.exe" -ArgumentList '/silent','/mergetasks=!runcode' -Wait
          Remove-Item "$env:TEMP\vscode.exe" -Force

      - name: Xuất thông tin kết nối
        shell: pwsh
        run: |
          Write-Host ""
          Write-Host "============================"
          Write-Host "  🖥️  WINDOWS RDP READY"
          Write-Host "============================"
          Write-Host "🪪 User: hyper"
          Write-Host "🔑 Pass: hyperdayroi"
          Write-Host "🌐 IP: $env:TAILSCALE_IP"
          Write-Host "============================"
          Write-Host ""
